### ISSUE TITLE
View Model Injection 

### ISSUE THREAD

**Issue by yingmu52** [gkaimakas/MVVMApp#2]
Hi, I have a question. 
in [PostListViewController](https://github.com/gkaimakas/MVVMApp/blob/master/MVVMApp/PostListViewController.swift#L30), I don't understand how you could inject the `PostListViewModel` using ` viewModel = inject(PostListViewModel.self)`, how do you pass the `PostProvider`, `UserProvider` and `CommentProvider` to `PostListViewModel`??

Could you explain the following code? 
```
 func inject<T>(_ type: T.Type) -> T {
        guard let object = (UIApplication.shared.delegate as? AppDelegate)?.container.resolve(type) else {
            fatalError("Could not inject \(type)")
        }
        
        return object
    }
```

**Comment by gkaimakas** [comment]
This is called dependency injection.

In AppDelegate I create a container and then register the necessary components e.g I register a `PostProvider`, a `UserProvider` and a `CommentProvider`. Then in the same container I register the `PostListViewModel` and I have the container supply the implementations for each of the dependencies (providers) needed.

You can probably learn more if you take a look in [Swinject](https://github.com/Swinject/Swinject)'s documentation. It has some great blog posts on the topic there.

The `inject<T>` function is simply a helper extension that I wrote to avoid duplicating the same code over and over again. It tries to retrieve an object of type `T` from the `container`. If the object is not present in the container it crashes the application and reports the missing object. The application needs to crash in order for the developer to resolve the issue
